heat_template_version: 2013-05-23

description: apt-cacher server

parameter_groups:
  - label: Network
    description: Network configuration.
    parameters:
      - net_id
      - subnet_id
      - floating_id

parameters:
  key_name:
    type: string
    description: Keypair to use.
  net_id:
    type: string
    description: Internal network ID.
  subnet_id:
    type: string
    description: Internal subnet ID.
  floating_id:
    type: string
    description: Floating subnet ID.

resources:
  server1:
    type: OS::Nova::Server
    properties:
      name: "apt-cacher"
      image: "ubuntu-precise-x64"
      flavor: "1vcpu512"
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: server1_port }
      user_data_format: "RAW"
      user_data: |
        #cloud-config

        bootcmd:
          - [ cloud-init-per, once, cacher-mkdir, mkdir, "/var/cache/apt-cacher-ng" ]

        fs_setup:
          - label: 'cacher-data'
            filesystem: 'ext4'
            device: '/dev/vdb'
        mounts:
          - [LABEL=cacher-data, /var/cache/apt-cacher-ng, ext4, defaults]

        apt_proxy: http://10.8.6.1:3142
        package_update: true
        package_upgrade: true
        packages:
          - apt-cacher-ng

        runcmd:
          - [ chown, "apt-cacher-ng:", "/var/cache/apt-cacher-ng" ]
          - [ service, apt-cacher-ng, restart ]

        final_message: "$TIMESTAMP: Cacher ready after $UPTIME seconds."

  cache_vol1:
    type: OS::Cinder::Volume
    properties:
      size: 20
      description: apt-cacher-ng cache

  cache_vol1_att:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { Ref: server1 }
      mountpoint: "/dev/vdb"
      volume_id: { Ref: cache_vol1 }

  cacher_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name: "apt-cacher"
      rules:
        - protocol: "tcp"
          remote_ip_prefix: "0.0.0.0/0"
          port_range_min: 3142
          port_range_max: 3142
        - protocol: "tcp"
          remote_ip_prefix: "0.0.0.0/0"
          port_range_min: 22
          port_range_max: 22

  server1_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: net_id }
      security_groups: [ Ref: cacher_secgroup ]
      fixed_ips:
        - subnet_id: { get_param: subnet_id }

  server1_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: floating_id}
      port_id: { get_resource: server1_port }

outputs:
  WebsiteURL:
    description: apt-cacher-ng's report URL
    value:
      str_replace:
        template: http://host:3142/acng-report.html
        params:
          host: { get_attr: [server1_floating_ip, floating_ip_address] }
  ProxyURL:
    description: apt-cacher-ng URL
    value:
      str_replace:
        template: http://host:3142/
        params:
          host: { get_attr: [server1_floating_ip, floating_ip_address] }
